extends RefCounted

# Phase G consumes the proven Phase E/F simulation through the same tuning-shaped
# content index. These are generic vertical-slice defaults, not campaign IDs or
# presentation-owned simulation values.

static func phase_e() -> Dictionary:
    return {
        "same_market_travel_index": 0.04,
        "default_travel_index": 0.48,
        "fatigue_recovery": 0.09,
        "fatigue_travel_gain": 0.30,
        "booking_base_coherence": 0.42,
        "booker_coherence_weight": 0.28,
        "road_agent_coherence_weight": 0.15,
        "program_coherence_weight": 0.14,
        "protect_coherence_bonus": 0.04,
        "fatigue_booking_penalty": 0.12,
        "drawing_overness_weight": 0.42,
        "drawing_momentum_weight": 0.18,
        "drawing_charisma_weight": 0.18,
        "drawing_market_fit_weight": 0.06,
        "drawing_program_weight": 0.08,
        "drawing_promotion_weight": 0.05,
        "drawing_media_weight": 0.03,
        "performance_weight": 0.34,
        "psychology_weight": 0.18,
        "booking_quality_weight": 0.26,
        "program_show_weight": 0.14,
        "show_quality_base": 0.08,
        "show_variance": 0.055,
        "fatigue_show_penalty": 0.14,
        "quality_crowd_weight": 0.48,
        "draw_crowd_weight": 0.32,
        "interest_crowd_weight": 0.20,
        "base_attendance": 900,
        "attendance_floor_multiplier": 0.35,
        "crowd_attendance_weight": 0.85,
        "draw_attendance_weight": 0.65,
        "prestige_attendance_weight": 0.25,
        "ticket_price_minor_units": 2500,
        "featured_momentum_bonus": 0.06,
        "show_momentum_scale": 0.22,
        "program_heat_scale": 0.18,
        "program_momentum_scale": 0.24,
        "momentum_retention": 0.62,
        "overness_momentum_conversion": 0.035,
        "overness_response_scale": 0.018,
        "overness_repetition_scale": 0.18,
        "featured_shine_scale": 0.08,
        "featured_heat_scale": 0.04,
        "supporting_heat_scale": 0.045,
        "supporting_shine_scale": 0.025,
        "program_momentum_retention": 0.72,
        "championship_prestige_scale": 0.015,
        "promotion_momentum_retention": 0.75,
        "promotion_show_signal_scale": 0.12,
        "breakthrough_overness_delta": 0.012,
        "journal_program_delta": 0.018,
        "overuse_grace_visits": 2,
        "audience_repetition_penalty": 0.035,
        "market_response_scale": 0.032,
        "market_overuse_penalty": 0.018,
        "market_interest_floor": 0.12,
        "influence_audience_gain": 0.028,
        "influence_business_gain": 0.018,
        "influence_media_gain": 0.018,
        "local_media_response_scale": 0.00000045,
        "media_familiarity_gain": 0.018,
        "influence_weights": {"audience": 0.40, "media": 0.25, "business": 0.25, "infrastructure": 0.10},
        "venue_cost_minor_units": 45000,
        "travel_cost_base_minor_units": 18000,
        "production_cost_minor_units": 12000,
        "monthly_overhead_minor_units": 30000,
        "local_tv_default_cost_minor_units": 10000,
        "local_tv_default_revenue_minor_units": 14000,
        "loss_stress_gain": 0.08,
        "profit_stress_recovery": 0.04,
        "low_cash_stress_gain": 0.08,
        "financial_stress_cash_threshold_minor_units": 200000,
        "hot_state": {
            "hot_threshold": 0.26,
            "cold_threshold": -0.26,
            "qualified_activation_chance": 0.33,
            "qualification_intensity_scale": 1.25,
            "duration_months": 3,
            "decay": 0.72,
            "minimum_intensity": 0.08,
            "propagation_scale": 0.15,
        },
    }

static func phase_f() -> Dictionary:
    return {
        "strategy_profiles": {
            "strategy.balanced": {"expansion": 0.58, "defense": 0.58, "creative": 0.62, "talent_aggression": 0.56, "loyalty": 0.60, "favorite_bias": 0.05, "cost_sensitivity": 0.55, "diplomacy": 0.50, "decision_noise": 0.025},
            "strategy.expansion": {"expansion": 0.90, "defense": 0.28, "creative": 0.55, "talent_aggression": 0.82, "loyalty": 0.42, "favorite_bias": 0.12, "cost_sensitivity": 0.25, "diplomacy": 0.35, "decision_noise": 0.045},
            "strategy.market_defense": {"expansion": 0.30, "defense": 0.92, "creative": 0.48, "talent_aggression": 0.40, "loyalty": 0.84, "favorite_bias": 0.18, "cost_sensitivity": 0.82, "diplomacy": 0.75, "decision_noise": 0.015},
        },
        "decision_noise_strength": 0.03,
        "recovery_stress_threshold": 0.58,
        "recovery_cash_threshold_minor_units": 220000,
        "recovery_minimum_touring_budget_minor_units": 45000,
        "recovery_budget_ratio": 0.62,
        "talent_roster_target": 4,
        "minimum_roster_size": 2,
        "renewal_window_months": 3,
        "default_contract_offer_minor_units": 12000,
        "scouting_familiarity_gain": 0.16,
        "default_scouting_quality": 0.58,
        "scouting_base_error": 0.28,
        "scouting_minimum_error": 0.025,
        "agreement_proposal_trust_threshold": 0.22,
        "agreement_acceptance_threshold": -0.05,
    }
